### PR TITLE
Search annotation by qualifiers

### PR DESCRIPTION
**Pull request by benjiec**
Hi Yaoyu, can you take a look at this? Also, I can't build the dockerfile locally, does that work? And how does on bump the version? Thanks.

### CODE REVIEW

**Comment by yaoyuyang** [comment]
The local docker should work though. What error are you seeing?

**Comment by yaoyuyang** [comment]
Also there seems to be a syntax error, the CI is failing.

**Comment by benjiec** [comment]
I just checked them in, but I am trying to load the local docker to test things. I can't because it says it can't install npm

**Comment by yaoyuyang** [comment]
Let me try it out locally!

**Comment by yaoyuyang** [comment]
I tried build locally using `docker-compose build --no-cache` and it built without errors. Can you try clean up your docker space? https://gist.github.com/yaoyuyang/c78c84aa0f69fa6b96a892664b3b2af9
Sometimes docker will report errors if there are not enough space on your docker space allocation.

**Comment by yaoyuyang** [comment]
For updating the version after pulled in, https://github.com/ginkgobioworks/edge#versioning.

**Pull request closed without merging**
